name: DigitalBits Core Prometheus Exporter

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade cloudsmith-cli 
        sudo apt-get install -y ruby ruby-dev rubygems build-essential
        sudo gem install --no-document fpm


    - name: Prepare for Deploy
      run: |
        fpm -f -s dir -t deb -n digitalbits-core-prometheus-exporter -v 1.0.0 \ 
          digitalbits_core_prometheus_exporter=/opt/digitalbits-core-prometheus-exporter

    - name: Deploy
      run: |
        export CLOUDSMITH_API_KEY=${{ secrets.CLOUDSMITH_API_KEY }}
        cloudsmith push deb xdb-foundation/digitalbits-core-prometheus-exporter/ubuntu/focal \
        digitalbits-core-prometheus-exporter-1.0.0.deb      