name: DigitalBits Core Prometheus Exporter

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade cloudsmith-cli 
        sudo apt-get install -y ruby ruby-dev rubygems build-essential
        sudo gem install --no-document fpm


    - name: Prepare for Deploy
      run: |
        fpm -f -s dir -t deb -n digitalbits-core-prometheus-exporter -v 1.0.1 digitalbits_core_prometheus_exporter/=/opt/digitalbits-core-prometheus-exporter/ digitalbits_core_prometheus_exporter/digitalbits-core-prometheus-exporter.service=/etc/systemd/system/digitalbits-core-prometheus-exporter.service

    - name: Deploy
      run: |
        export CLOUDSMITH_API_KEY=${{ secrets.CLOUDSMITH_API_KEY }}
        cloudsmith push deb xdb-foundation/digitalbits-core-prometheus-exporter/ubuntu/focal \
        digitalbits-core-prometheus-exporter_1.0.1_amd64.deb     