 name: WindowsCI

 on: push
 jobs:
  windowsbuild:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Install dependencies
      run: |
        pip install pyinstaller
        pip install prometheus_client

    - name: Build Binaries
      run: |
        pyinstaller -wF digitalbits_core_prometheus_exporter/exporter.py
        mv dist\exporter dist\prometheus_exporter-windows-amd64

    - name: Get Latest Tag
      id: previoustag
      uses: WyriHaximus/github-action-get-previous-tag@v1

    - uses: ncipollo/release-action@v1
      with:
          allowUpdates: true
          artifacts: "dist/prometheus_exporter-darwin-amd64"
          tag: ${{ steps.previoustag.outputs.tag }}
          bodyFile: "README.md"
          omitBodyDuringUpdate: true
          token: ${{ secrets.GITHUB_TOKEN }}  